packages:
  - packages/*

allowBuilds:
  esbuild: true
  webgpu: true

auditConfig:
  ignoreGhsas:
    - GHSA-86w9-cpqp-85rv

linkWorkspacePackages: true

minimumReleaseAgeExclude:
  - three
  - '@vitest/coverage-v8'
  - '@vitest/mocker'
  - '@vitest/pretty-format'
  - '@vitest/spy'
  - '@vitest/utils'
  - vitest
  - fidelity-kit
