// Generated by test/browser/run-network-parity-chrome.mjs --golden. Do not edit by hand.

import type { NetworkDigest } from './golden.js';

export const GOLDEN_DIGESTS: Record<string, NetworkDigest> = {};
